.github/workflows/ping_canadian_feeds.yml

name: Canadian Feed Uptime Pings

on:
schedule:
- cron: ‘0 * * * *’  # every hour on the hour
workflow_dispatch:

jobs:
ping-canadian-feeds:
runs-on: ubuntu-latest

steps:
  - name: Check out repo
    uses: actions/checkout@v4

  - name: Install dependencies
    run: |
      pip install requests feedparser

  - name: Ping CBC & CTV feeds
    id: ping
    run: |
      python3 - << 'EOF'
      import json, requests, feedparser
      from datetime import datetime

      feeds = {
        "CBC": "https://rss.cbc.ca/lineup/topstories.xml",
        "CTV": "https://www.ctvnews.ca/rss/ctvnews-ca-canada-1.2089050"
      }

      timestamp = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
      record = {"timestamp": timestamp}
      for name, url in feeds.items():
          try:
              r = requests.get(url, timeout=10); r.raise_for_status()
              record[name] = bool(feedparser.parse(r.content).entries)
          except:
              record[name] = False

      # Load existing uptime.json or init
      path = 'uptime.json'
      try:
          data = json.load(open(path))
      except:
          data = []

      data.append(record)
      # Keep last 168 entries (~7 days hourly)
      data = data[-168:]

      with open(path, 'w') as f:
          json.dump(data, f, indent=2)
      EOF

  - name: Commit & push uptime.json
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git add uptime.json
      git commit -m "Add uptime ping ${{ steps.ping.outputs.timestamp }}" || echo "No changes"
      git push


⸻

.github/workflows/pages-build-deployment.yml

name: Deploy GitHub Pages

on:
push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: './'
      publish_branch: gh-pages
      user_name: github-actions[bot]
      user_email: 41898282+github-actions[bot]@users.noreply.github.com