name: Update latest.txt
on:
  schedule:
    - cron: '30 10 * * *'  # 6:30 AM Eastern
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install requests feedparser
      - name: Generate latest.txt
        run: python generate_latest.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt
          git commit -m "Auto-update latest.txt for $(date +'%Y-%m-%d')" || echo "No changes"
          git push