name: Auto-update latest.txt

# Trigger on schedule (6:30 AM Eastern) and manual dispatch
on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python 3.x
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --no-cache-dir requests feedparser

      # 4. Run the generator
      - name: Generate latest.txt
        run: python generate_latest.py

      # 5. Commit & push changes (if any)
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt
          git diff --quiet --exit-code || \
            (git commit -m "Auto-update latest.txt for $(date '+%Y-%m-%d')" && git push)