name: Auto-update latest.txt

on:
  schedule:
    - cron: '30 10 * * *'   # 6:30 AM EDT
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install requests feedparser python-dateutil

      - name: Generate latest.txt
        run: python generate_latest.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt cache.json
          git commit -m "Auto-update briefing for $(date +'%Y-%m-%d')" || echo "No changes"
          git push