name: Update latest.txt

on:
  # Daily at 6:30 AM Eastern (10:30 UTC)
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install your dependencies
      - name: Install dependencies
        run: |
          pip install requests feedparser python-dateutil

      # 4. Run the generator
      - name: Generate latest.txt
        run: python generate_latest.py

      # 5. Commit & push results
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt cache.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-update latest.txt for $(date '+%Y-%m-%d')"
          git push