name: Update latest.txt

on:
  schedule:
    - cron: '30 10 * * *'       # 6:30 AM Eastern daily
  workflow_dispatch:          # so you can click “Run workflow” in the UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Generate latest.txt
        run: python generate_latest.py

      - name: Commit & push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt
          git commit -m "Auto-update latest.txt for $(date +'%Y-%m-%d')" || echo "No changes"
          git push