name: Daily News Briefing Update

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 6:00 AM ET, Mon–Fri
  workflow_dispatch:       # Manual trigger

jobs:
  update-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest.txt from content source
        run: |
          curl -L -s https://hc-news-briefing-feed.github.io/generated/latest.txt -o latest.txt

      - name: Commit and push updated file
        run: |
          git config user.name "news-bot"
          git config user.email "newsbot@example.com"
          git add -A
          git commit -am "Auto-update latest.txt for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
