name: Update latest.txt

on:
  schedule:
    - cron: '30 10 * * *'  # 6:30 AM Eastern (10:30 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate latest.txt
        run: |
          echo "Morning News Briefing – $(date '+%B %d, %Y')" > latest.txt
          echo "" >> latest.txt
          echo "INTERNATIONAL HEADLINES" >> latest.txt
          echo "• Macron calls snap French election. {June 20, 2025 (Reuters)}" >> latest.txt
          echo "• Biden meets G7 leaders on AI. {June 20, 2025 (Globe and Mail)}" >> latest.txt
          echo "" >> latest.txt
          echo "NATIONAL HEADLINES" >> latest.txt
          echo "• Bank of Canada holds interest rate. {June 20, 2025 (CBC)}" >> latest.txt
          echo "" >> latest.txt
          echo "PUBLIC HEALTH & AI POLICY" >> latest.txt
          echo "• PHAC expands use of GIS for disease monitoring. {June 20, 2025 (CBC)}" >> latest.txt
          echo "• Canada Digital Credentials pilot in 3 provinces. {June 20, 2025 (The Globe and Mail)}" >> latest.txt
          echo "" >> latest.txt
          echo "— End of briefing —" >> latest.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt
          git commit -m "Auto-update latest.txt for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
