name: Daily News Briefing Update

on:
  schedule:
    - cron: '0 10 * * 1-5'   # Runs at 6:00 AM ET, Monday–Friday
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest.txt from source
        run: |
          curl -L -s https://hc-news-briefing-feed.github.io/generated/latest.txt -o latest.txt

      - name: Commit and push updated file
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Auto-update latest.txt for $(date '+%Y-%m-%d')"
