name: Update Daily News Briefing

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 6:00 AM ET (10:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install feedparser transformers torch

      - name: Run news briefing generator
        run: python generate_latest.py

      - name: Commit & push updated briefing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add latest.txt
          git commit -m "Auto-update latest.txt for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push