name: Daily News Briefing Update

on:
  schedule:
    - cron: '0 10 * * 1-5'   # Runs at 6:00 AM ET Mon–Fri
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest.txt from content source
        run: |
          curl -L -s https://hc-news-briefing-feed.github.io/generated/latest.txt -o latest.txt

      - name: Auto-commit updated file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update latest.txt for $(date '+%Y-%m-%d')"
