name: Update latest.txt with news and weather

on:
  schedule:
    - cron: '30 10 * * *'   # 10:30 UTC → 6:30 AM ET daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-briefing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: List repo root and check script
        run: |
          echo "Contents of repo root:"
          ls -lah .
          echo "--- Checking generate_latest.py ---"
          if [ ! -f generate_latest.py ]; then
            echo "❌ generate_latest.py not found in repo root!" >&2
            exit 1
          fi
          head -n 5 generate_latest.py

      - name: Generate latest.txt
        run: python generate_latest.py

      - name: Commit & push updated briefing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.txt
          git commit -m "Auto-update latest.txt for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push